# -*- coding: utf-8 -*-
"""UTS-Yossica-23-MTTK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yyUDK5sR8rkokmAFcWKyxERCbYbp7xaj

**SOAL NO 2**

Buatlah sebuah tuple yang berisi beberapa nama buah-buahan
"""

buah=('anggur','semangka','kiwi')
print(buah)

"""Implementasi program untuk menggabungkan dua tuple menjadi satu"""

huruf1=('a','b','c')
huruf2=('d','e','f')
h=huruf1+huruf2
print(h)

"""buatlah tuple berisi nilai-nilai numerik dan implemnetasi fungsi untuk menghitung jumlah elemen-elemen tuple tersebut"""

nilai = (25, 4, 5, 6, 7)
total = sum(nilai)
print(total)

"""**SOAL NO 1**

buatlah kode program untuk struktur inheritance dengan 3 jenis: 1. package, 2. overnight packeg, 3. twodays package. buatlah agar user menginput data-data yang dibutuhkan sender name=string, receivernam=string, senderaddress, receiveraddress, weight=float, kecuali untuk atribut feeperounce=float, overnightfeeperounce, dan flatfee. karena ketiganya atribut statis. user diminta memilih opsi pengiriman yang diinginkan bisa 1. package, 2. overnight packeg, 3. twodays package. ketika fungsi displayinfo() dijalankan, informasi pengirim, penerima, jenis pengirim, dan total biaya kirim ditampilkan.

Untuk rumus =
package cost = weight * fee per ounce
overnight package cost = weight *(fee per ounce + overnight fee per ounce)
two day package cost = (weight * fee per ounce)+ flat fee
"""

class Package:
    def __init__(s, sender_name, receiver_name, sender_address, receiver_address, weight):
        s.sender_name = sender_name
        s.receiver_name = receiver_name
        s.sender_address = sender_address
        s.receiver_address = receiver_address
        s.weight = weight

    def display_info(s):
        print("Sender Name:", s.sender_name)
        print("Receiver Name:", s.receiver_name)
        print("Sender Address:", s.sender_address)
        print("Receiver Address:", s.receiver_address)

class OvernightPackage(Package):
    fee_per_ounce = 0.5
    overnight_fee_per_ounce = 1.0

    def calculate_cost(s):
        return s.weight * (s.fee_per_ounce + s.overnight_fee_per_ounce)

class TwoDaysPackage(Package):
    fee_per_ounce = 0.5
    flat_fee = 5.0

    def calculate_cost(s):
        return (s.weight * s.fee_per_ounce) + s.flat_fee

sender_name = input("sender name: ")
receiver_name = input("receiver name: ")
sender_address = input("sender address: ")
receiver_address = input("receiver address: ")
weight = float(input("weight of the package: "))
option = input("1  Package, 2 Overnight for Package, 3  Two Days Package: ")